spring.application.name=client
#
# oauth server ~= provider
spring.security.oauth2.client.provider.spring-provider.issuer-uri=http://localhost:9090
#
# oauth client configured to use provider
spring.security.oauth2.client.registration.ui.provider=spring-provider
spring.security.oauth2.client.registration.ui.client-id=spring
spring.security.oauth2.client.registration.ui.client-secret=spring
spring.security.oauth2.client.registration.ui.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.ui.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.ui.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.ui.scope=openid,profile
